### ISSUE TITLE
SCD Idle Power Draw

### ISSUE THREAD

**Issue by thejimster82** [UVA-DSI/sensenet#2]
When the SCD is connected and taking readings, it increases idle power draw by about 4.3mA. When it is immediately disabled via sending 0x0104 on the I2C bus in setup() this is not an issue. However, when it is disabled and then re-enabled and read from and then disabled again, the current draw never goes back down. Could solve with a MOSFET or BJT if space allows.

**Comment by unixjazz** [comment]
The datasheet describes a self-calibration period in which the sensor needs to stay on. By turning it on and off, we have to redo the self-calibration. I would suggest just increasing the sampling frequency (by a lot), so there is some power saving. This is also described in the data sheet for achieving lower power modes with the SCD30. Otherwise, it is better to rely on other sensors for low-power applications.

Closing this issue and marking as "work as designed" (except for the curious behavior you describe, which, I guess is something to be fixed in the firmware of the MCU that is shipped with the sensor itself).
